[package]
name = "solana-indexer-macros"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

[lib]
crate-type = ["rlib"]
